
import AlasOnix from '@/assets/img/portada_libro.jpg'
import RebeccaYarros from '@/assets/img/portada_libro.jpg'

const librosEjemplo = [
    {
        id: "1",
        titulo: "Un Fuego Azul",
        autor: "Pedro Feijoo",
        precio: 249,
        imagen: AlasOnix,
    },
    {
        id: "2",
        titulo: "Eres Todo Para Mí",
        autor: "Sylvia Day",
        precio: 199,
        imagen: AlasOnix,
    },
    {
        id: "3",
        titulo: "Río Bravo",
        autor: "Julio Vaquero",
        precio: 215,
        imagen: AlasOnix,
    },
    {
        id: "1",
        titulo: "Un Fuego Azul",
        autor: "Pedro Feijoo",
        precio: 249,
        imagen: AlasOnix,
    },
    {
        id: "2",
        titulo: "Eres Todo Para Mí",
        autor: "Sylvia Day",
        precio: 199,
        imagen: AlasOnix,
    },
    {
        id: "3",
        titulo: "Río Bravo",
        autor: "Julio Vaquero",
        precio: 215,
        imagen: AlasOnix,
    },
    {
        id: "1",
        titulo: "Un Fuego Azul",
        autor: "Pedro Feijoo",
        precio: 249,
        imagen: AlasOnix,
    },
    {
        id: "2",
        titulo: "Eres Todo Para Mí",
        autor: "Sylvia Day",
        precio: 199,
        imagen: AlasOnix,
    },
    {
        id: "3",
        titulo: "Río Bravo",
        autor: "Julio Vaquero",
        precio: 215,
        imagen: AlasOnix,
    },
    {
        id: "1",
        titulo: "Un Fuego Azul",
        autor: "Pedro Feijoo",
        precio: 249,
        imagen: AlasOnix,
    },
    {
        id: "2",
        titulo: "Eres Todo Para Mí",
        autor: "Sylvia Day",
        precio: 199,
        imagen: AlasOnix,
    },
    {
        id: "3",
        titulo: "Río Bravo",
        autor: "Julio Vaquero",
        precio: 215,
        imagen: AlasOnix,
    },
    {
        id: "1",
        titulo: "Un Fuego Azul",
        autor: "Pedro Feijoo",
        precio: 249,
        imagen: AlasOnix,
    },
    {
        id: "2",
        titulo: "Eres Todo Para Mí",
        autor: "Sylvia Day",
        precio: 199,
        imagen: AlasOnix,
    },
    {
        id: "3",
        titulo: "Río Bravo",
        autor: "Julio Vaquero",
        precio: 215,
        imagen: AlasOnix,
    },
    {
        id: "1",
        titulo: "Un Fuego Azul",
        autor: "Pedro Feijoo",
        precio: 249,
        imagen: AlasOnix,
    },
    {
        id: "2",
        titulo: "Eres Todo Para Mí",
        autor: "Sylvia Day",
        precio: 199,
        imagen: AlasOnix,
    },
    {
        id: "3",
        titulo: "Río Bravo",
        autor: "Julio Vaquero",
        precio: 215,
        imagen: AlasOnix,
    },
    {
        id: "1",
        titulo: "Un Fuego Azul",
        autor: "Pedro Feijoo",
        precio: 249,
        imagen: AlasOnix,
    },
    {
        id: "2",
        titulo: "Eres Todo Para Mí",
        autor: "Sylvia Day",
        precio: 199,
        imagen: AlasOnix,
    },
    {
        id: "3",
        titulo: "Río Bravo",
        autor: "Julio Vaquero",
        precio: 215,
        imagen: AlasOnix,
    },
];

export {librosEjemplo};